version: '3'
services:
  soldier:
    build: soldier
    environment:
      - SORCERER_HOST=sorcerer
      - SORCERER_PORT=5001
    depends_on:
      - sorcerer
  sorcerer:
    build: sorcerer
    environment:
      - SORCERER_PORT=5001
    expose:
      - "5000"
